# Generated by Django 5.1.7 on 2025-03-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="feedback",
            field=models.TextField(blank=True, null=True),
        ),
    ]
