# Generated by Django 5.1.7 on 2025-03-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0002_submission_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="expected_sql",
            field=models.TextField(blank=True, null=True),
        ),
    ]
